spring:
  profiles:
    active:
      - ${SPRING_ENV:dev}
      - ${DB_TYPE:pgsql}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    generate-ddl: true
logging:
  level:
    root: info
