server:
  port: 8080
spring:
  application:
    name: geom-admin
  profiles:
    active:
      - ${SPRING_ENV:dev}
      - ${DB_TYPE:pgsql}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
logging:
  level:
    root: info
