server:
  port: 8080
spring:
  application:
    name: geom-admin
  profiles:
    active:
      - ${DB_TYPE:pgsql}
      - ${CACHE_TYPE:in-memory}
      - ${ENV:prod}
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    generate-ddl: true
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  token-style: tik
logging:
  level:
    root: info
geom:
  system:
    id-generator: ${ID_GENERATOR:snowflake}
    sa-token-dao: ${SA_TOKEN_DAO:default}
