spring:
  data:
    redis:
      url: redis://${REDIS_URL:localhost:6379}
      database: ${REDIS_DB:0}
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 3000ms
geom:
  system:
    id-generator: ${ID_GENERATOR:redis}
    sa-token-dao: ${SA_TOKEN_DAO:redis}
