server:
  port: 8080
spring:
  application:
    name: geom-admin
  profiles:
    active:
      - ${SPRING_ENV:dev}
      - ${DB_TYPE:pgsql}
      - ${CACHE_TYPE:in-memory}
  jackson:
    visibility:
      ALL: ANY
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    generate-ddl: true
logging:
  level:
    root: info
bean:
  id-generator: snowflake
