server:
  port: @app.port@
spring:
  application:
    name: geom-admin-api
  profiles:
    active:
      - ${DB_TYPE:pgsql}
      - ${ENV:prod}
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
logging:
  level:
    root: info
geom:
  system:
    id-generator: ${ID_GENERATOR:snowflake}
